# Troca capslock por esc
#setxkbmap -option caps:swapescape
# General Aliases
# ls
LS_OPTIONS='--group-directories-first --color=auto'
alias ls='ls $LS_OPTIONS'
alias la='ls -lA'
alias ll='ls -lNh'
alias l.='ll -d .*' #apenas ocultos

# Vi
[ -f ~/dotfiles/vim/general/essential.vim ] && alias vi='vim -u ~/dotfiles/vim/general/essential.vim'

# Eclipse
#[ -f /home/romulo/eclipse/java-2022-03/eclipse/eclipse ] && \
#    alias eclipse='/home/romulo/eclipse/java-2022-03/eclipse/eclipse'

# grep
GREP_OPTIONS='--color=auto'
alias grep='grep $GREP_OPTIONS'
alias fgrep='fgrep $GREP_OPTIONS'
alias egrep='egrep $GREP_OPTIONS'

# download de videos
alias yt='youtube-dl --add-metadata -ic'
# download apenas do audio
alias yta='yt -x'

# Fedora Aliases
if grep -iq 'fedora' /etc/os-release; then
  alias dnfi="sudo dnf install"

  _package_query() {
      local cache="/var/cache/dnf/packages.db"
      sqlite3 $cache "SELECT * FROM available WHERE pkg LIKE '$1%';"
  }

  _autocomplete_dnf() {
      mapfile -t COMPREPLY < <(_package_query "$2");
  }
  complete -F _autocomplete_dnf dnfi
fi

# SOURCE BASH.CONF
[ -f ~/dotfiles/bash/bash.conf ] && . ~/dotfiles/bash/bash.conf
