# General Aliases
alias la='ls -lA'
alias ll='ls -l'

# Fedora Aliases
if grep -iq 'fedora' /etc/os-release; then
  alias dnfi="sudo dnf install"

  _package_query() {
      local cache="/var/cache/dnf/packages.db"
      sqlite3 $cache "SELECT * FROM available WHERE pkg LIKE '$1%';"
  }

  _autocomplete_dnf() {
      mapfile -t COMPREPLY < <(_package_query "$2");
  }
  complete -F _autocomplete_dnf dnfi
fi
