# .bashrc - configure bash environment
# aponte seu .bashrc para este arquivo
EDITOR="/usr/bin/vim"
PROMPT_DIRTRIM=1
if [ "$PS1" ]; then
  PS1=":\w\\$ "
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# create directory if it doesn't exist
[[ -d $HOME/.local/bin ]] || mkdir $HOME/.local/bin

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Arclinkfetch require Python2
if ! [[ "$PATH" =~ "/opt/sismo/arclinkfetch/bin" ]]
then
    PATH="$PATH:/opt/sismo/arclinkfetch/bin"
fi

# MSI miniseed inspector (https://github.com/iris-edu/msi)
if ! [[ "$PATH" =~ "/opt/sismo/msi-3.8" ]]
then
    PATH="$PATH:/opt/sismo/msi-3.8"
fi

# Slinktool (https://github.com/iris-edu/slinktool)
if ! [[ "$PATH" =~ "/opt/sismo/slinktool" ]]
then
    PATH="$PATH:/opt/sismo/slinktool"
fi

# Anaconda3
ANACONDA_HOME="$HOME/anaconda3"
if ! [[ "$PATH" =~ "${ANACONDA_HOME}/bin:${ANACONDA_HOME}/condabin" ]]
then
    PATH="$PATH:${ANACONDA_HOME}/bin:${ANACONDA_HOME}/condabin"
fi
export PATH

# Android Studio
if ! [[ "$PATH" =~ "/opt/android-studio/bin" ]]
then
    PATH="$PATH:/opt/android-studio/bin"
fi
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# aliases 
. ~/dotfiles/bash/bash_aliases
# functions

